# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PEMO' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON', '4.0.0-alpha.1'
  pod 'Toaster', '~> 2.1'
  pod 'KUIPopOver'
  
  use_frameworks!

  # Pods for PEMO

end
